[default.general]
chip = "STM32G474CEUx"

[default.probe]
usb_vid = "0483"
usb_pid = "3748"
serial = "78C28808"

[default.flashing]
enabled = true

[default.rtt]
enabled = true
up_channels = [
    { channel = 0, mode = "BlockIfFull", format = "Defmt", show_location = true, show_timestamps = true },
    { channel = 1, mode = "BlockIfFull", format = "String", show_timestamps = false },
    { channel = 2, mode = "BlockIfFull", format = "BinaryLE", show_timestamps = false, socket = "127.0.0.1:1234" },
]
down_channels = [{ channel = 0, mode = "BlockIfFull" }]
tabs = [
    { up_channel = 0, name = "Logs" },
    { up_channel = 1, down_channel = 0, name = "Terminal" },
    { up_channel = 2, name = "wav", hide = true },
]
